//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktywuj użytkownika.
        /// </summary>
        public static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data dodania.
        /// </summary>
        public static string AddDate {
            get {
                return ResourceManager.GetString("AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj dokument.
        /// </summary>
        public static string AddDoc {
            get {
                return ResourceManager.GetString("AddDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj nowego użytkownika.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypisz.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przydziel dokument.
        /// </summary>
        public static string AssignDoc {
            get {
                return ResourceManager.GetString("AssignDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przypisany użytkownik.
        /// </summary>
        public static string AssignedUser {
            get {
                return ResourceManager.GetString("AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anuluj.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień login.
        /// </summary>
        public static string ChangeLogin {
            get {
                return ResourceManager.GetString("ChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień hasło.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień dane osobowe.
        /// </summary>
        public static string ChangePersonalData {
            get {
                return ResourceManager.GetString("ChangePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmień rangę.
        /// </summary>
        public static string ChangeRank {
            get {
                return ResourceManager.GetString("ChangeRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana hasła użytkownika:.
        /// </summary>
        public static string ChangingPasswordColon {
            get {
                return ResourceManager.GetString("ChangingPasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana danych osobowych:.
        /// </summary>
        public static string ChangingPersonalDataColon {
            get {
                return ResourceManager.GetString("ChangingPersonalDataColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana loginu użytkownika:.
        /// </summary>
        public static string ChangingUserLoginColon {
            get {
                return ResourceManager.GetString("ChangingUserLoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmiana roli użytkownika:.
        /// </summary>
        public static string ChangingUserRoleColon {
            get {
                return ResourceManager.GetString("ChangingUserRoleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wybierz rolę:.
        /// </summary>
        public static string ChooseRoleColon {
            get {
                return ResourceManager.GetString("ChooseRoleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyczyść.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klient.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdź wykonanie.
        /// </summary>
        public static string ConfirmDone {
            get {
                return ResourceManager.GetString("ConfirmDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatwierdzony.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatw..
        /// </summary>
        public static string ConfirmedShort {
            get {
                return ResourceManager.GetString("ConfirmedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utworzono nową bazę danych z kontem administratora.   
        ///Login: Admin 
        ///Hasło: Admin
        ///Możesz się zalogować z wykorzystaniem powyższych danych..
        /// </summary>
        public static string DbCreatedBoxText {
            get {
                return ResourceManager.GetString("DbCreatedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało się utworzyć bazy danych. Sprawdź czy na urządzeniu jest zainstalowane wymagane środowisko!.
        /// </summary>
        public static string DbNotCreatedBoxText {
            get {
                return ResourceManager.GetString("DbNotCreatedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zdezaktywuj użytkownika.
        /// </summary>
        public static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Termin wykonania.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuń dokument.
        /// </summary>
        public static string DeleteDoc {
            get {
                return ResourceManager.GetString("DeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa dokumentu.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ dokumentu.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data wykonania.
        /// </summary>
        public static string DoneDate {
            get {
                return ResourceManager.GetString("DoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edytuj dokument.
        /// </summary>
        public static string EditDoc {
            get {
                return ResourceManager.GetString("EditDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj nowy login:.
        /// </summary>
        public static string EnterNewLoginColon {
            get {
                return ResourceManager.GetString("EnterNewLoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wprowadź nowe hasło:.
        /// </summary>
        public static string EnterNewPasswordColon {
            get {
                return ResourceManager.GetString("EnterNewPasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię:.
        /// </summary>
        public static string FirstNameColon {
            get {
                return ResourceManager.GetString("FirstNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wygeneruj przykładowe dokumenty.
        /// </summary>
        public static string GenerateRandomFiles {
            get {
                return ResourceManager.GetString("GenerateRandomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Użytkownik o takim loginie już istnieje w bazie danych! Wybierz inny login..
        /// </summary>
        public static string LoginAlreadyExistsWarning {
            get {
                return ResourceManager.GetString("LoginAlreadyExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string LoginColon {
            get {
                return ResourceManager.GetString("LoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowe dane logowania. Sprawdź login i hasło.
        /// </summary>
        public static string LoginDataNotCorrect {
            get {
                return ResourceManager.GetString("LoginDataNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proces logowania nie powiódł się. Sprawdź czy posiadasz odpowiednie uprawnienia.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login musi składać się z conajmniej dwóch znaków!.
        /// </summary>
        public static string LoginMinLengthWarning {
            get {
                return ResourceManager.GetString("LoginMinLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie odnaleziono loginu w bazie..
        /// </summary>
        public static string LoginNotFound {
            get {
                return ResourceManager.GetString("LoginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login zbyt krótki!.
        /// </summary>
        public static string LoginTooShortWarning {
            get {
                return ResourceManager.GetString("LoginTooShortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaloguj.
        /// </summary>
        public static string LoginVerb {
            get {
                return ResourceManager.GetString("LoginVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyloguj.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj użytkownikiem:.
        /// </summary>
        public static string ManageUserColon {
            get {
                return ResourceManager.GetString("ManageUserColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zarządzaj użytkownikami.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznacz jako wykonany.
        /// </summary>
        public static string MarkAsDone {
            get {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwa.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imię i Nazwisko muszą składać się z conajmniej dwóch znaków!.
        /// </summary>
        public static string NamesMinLengthWarning {
            get {
                return ResourceManager.GetString("NamesMinLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy klient.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy typ dokumetu.
        /// </summary>
        public static string NewDocType {
            get {
                return ResourceManager.GetString("NewDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy język.
        /// </summary>
        public static string NewLanguage {
            get {
                return ResourceManager.GetString("NewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowy użytkownik:.
        /// </summary>
        public static string NewUserColon {
            get {
                return ResourceManager.GetString("NewUserColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Następna strona.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baza danych nie odnaleziona! Jeżeli to pierwsze uruchomienie aplikacji wybierz &apos;Tak&apos; aby utworzyć nową bazę danych..
        /// </summary>
        public static string NoDbBoxText {
            get {
                return ResourceManager.GetString("NoDbBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak połączenia z bazą danych!.
        /// </summary>
        public static string NoDbBoxTitle {
            get {
                return ResourceManager.GetString("NoDbBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie wybrano roli!.
        /// </summary>
        public static string NoRoleChosenWarning {
            get {
                return ResourceManager.GetString("NoRoleChosenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyświetl statystyki.
        /// </summary>
        public static string OpenStatisticsWindow {
            get {
                return ResourceManager.GetString("OpenStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło:.
        /// </summary>
        public static string PasswordColon {
            get {
                return ResourceManager.GetString("PasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasła nie są jednakowe!.
        /// </summary>
        public static string PasswordsNotSameWarning {
            get {
                return ResourceManager.GetString("PasswordsNotSameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło za krótkie! minimalny rozmiar to 4 znaki.
        /// </summary>
        public static string PasswordTooShortWarning {
            get {
                return ResourceManager.GetString("PasswordTooShortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poprzednia strona.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranga.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranga:.
        /// </summary>
        public static string RankColon {
            get {
                return ResourceManager.GetString("RankColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odpowiedzialny.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyszukaj.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozmiar.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język źródłowy.
        /// </summary>
        public static string SourceLang {
            get {
                return ResourceManager.GetString("SourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko:.
        /// </summary>
        public static string SurnameColon {
            get {
                return ResourceManager.GetString("SurnameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Język docelowy.
        /// </summary>
        public static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tłumacz.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
    }
}
