//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfApp.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate User.
        /// </summary>
        public static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date added.
        /// </summary>
        public static string AddDate {
            get {
                return ResourceManager.GetString("AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add document.
        /// </summary>
        public static string AddDoc {
            get {
                return ResourceManager.GetString("AddDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new user.
        /// </summary>
        public static string AddNewUser {
            get {
                return ResourceManager.GetString("AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assign {
            get {
                return ResourceManager.GetString("Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign document.
        /// </summary>
        public static string AssignDoc {
            get {
                return ResourceManager.GetString("AssignDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned user.
        /// </summary>
        public static string AssignedUser {
            get {
                return ResourceManager.GetString("AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel confirmation.
        /// </summary>
        public static string CancelConfirm {
            get {
                return ResourceManager.GetString("CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language:.
        /// </summary>
        public static string ChangeLanguageColon {
            get {
                return ResourceManager.GetString("ChangeLanguageColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change login.
        /// </summary>
        public static string ChangeLogin {
            get {
                return ResourceManager.GetString("ChangeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal data.
        /// </summary>
        public static string ChangePersonalData {
            get {
                return ResourceManager.GetString("ChangePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change rank.
        /// </summary>
        public static string ChangeRank {
            get {
                return ResourceManager.GetString("ChangeRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password:.
        /// </summary>
        public static string ChangingPasswordColon {
            get {
                return ResourceManager.GetString("ChangingPasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change personal data:.
        /// </summary>
        public static string ChangingPersonalDataColon {
            get {
                return ResourceManager.GetString("ChangingPersonalDataColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change login:.
        /// </summary>
        public static string ChangingUserLoginColon {
            get {
                return ResourceManager.GetString("ChangingUserLoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change role:.
        /// </summary>
        public static string ChangingUserRoleColon {
            get {
                return ResourceManager.GetString("ChangingUserRoleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose role:.
        /// </summary>
        public static string ChooseRoleColon {
            get {
                return ResourceManager.GetString("ChooseRoleColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name too short!.
        /// </summary>
        public static string ClientNameLengthWarning {
            get {
                return ResourceManager.GetString("ClientNameLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm document.
        /// </summary>
        public static string ConfirmDocument {
            get {
                return ResourceManager.GetString("ConfirmDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm done.
        /// </summary>
        public static string ConfirmDone {
            get {
                return ResourceManager.GetString("ConfirmDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conf..
        /// </summary>
        public static string ConfirmedShort {
            get {
                return ResourceManager.GetString("ConfirmedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue?.
        /// </summary>
        public static string ContinueQuestion {
            get {
                return ResourceManager.GetString("ContinueQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database created!
        ///Login: Admin 
        ///Hasło: Admin
        ///Please use credentials above to log in..
        /// </summary>
        public static string DbCreatedBoxText {
            get {
                return ResourceManager.GetString("DbCreatedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database creation failed!.
        /// </summary>
        public static string DbNotCreatedBoxText {
            get {
                return ResourceManager.GetString("DbNotCreatedBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate user.
        /// </summary>
        public static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string DeleteBoxTitle {
            get {
                return ResourceManager.GetString("DeleteBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document.
        /// </summary>
        public static string DeleteDoc {
            get {
                return ResourceManager.GetString("DeleteDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You intend to permanently delete data from the database. This operation is irreversible and may disturb the integrity of the remaining data!
        ///Continue?.
        /// </summary>
        public static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Doc {
            get {
                return ResourceManager.GetString("Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name.
        /// </summary>
        public static string DocName {
            get {
                return ResourceManager.GetString("DocName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document name too short!.
        /// </summary>
        public static string DocNameLengthWarning {
            get {
                return ResourceManager.GetString("DocNameLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source and target languages are the same!.
        /// </summary>
        public static string DocSameLanguagesWarning {
            get {
                return ResourceManager.GetString("DocSameLanguagesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document size NOK!.
        /// </summary>
        public static string DocSizeWarning {
            get {
                return ResourceManager.GetString("DocSizeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type.
        /// </summary>
        public static string DocType {
            get {
                return ResourceManager.GetString("DocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodument Type name too short!.
        /// </summary>
        public static string DocTypeLengthWarning {
            get {
                return ResourceManager.GetString("DocTypeLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date done.
        /// </summary>
        public static string DoneDate {
            get {
                return ResourceManager.GetString("DoneDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit document.
        /// </summary>
        public static string EditDoc {
            get {
                return ResourceManager.GetString("EditDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new login:.
        /// </summary>
        public static string EnterNewLoginColon {
            get {
                return ResourceManager.GetString("EnterNewLoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert new password:.
        /// </summary>
        public static string EnterNewPasswordColon {
            get {
                return ResourceManager.GetString("EnterNewPasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstNameColon {
            get {
                return ResourceManager.GetString("FirstNameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random documents will be created in quantity of: .
        /// </summary>
        public static string GenerateRandomDocs {
            get {
                return ResourceManager.GetString("GenerateRandomDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create random documents.
        /// </summary>
        public static string GenerateRandomDocsBoxTitle {
            get {
                return ResourceManager.GetString("GenerateRandomDocsBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create random documents.
        /// </summary>
        public static string GenerateRandomFiles {
            get {
                return ResourceManager.GetString("GenerateRandomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name too short!.
        /// </summary>
        public static string LanguageNameLengthWarning {
            get {
                return ResourceManager.GetString("LanguageNameLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login already exists in database! Please choose different login..
        /// </summary>
        public static string LoginAlreadyExistsWarning {
            get {
                return ResourceManager.GetString("LoginAlreadyExistsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string LoginColon {
            get {
                return ResourceManager.GetString("LoginColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login data not correct. Check login and password.
        /// </summary>
        public static string LoginDataNotCorrect {
            get {
                return ResourceManager.GetString("LoginDataNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login process failed! Check your permissions.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login too short!.
        /// </summary>
        public static string LoginMinLengthWarning {
            get {
                return ResourceManager.GetString("LoginMinLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login not found!.
        /// </summary>
        public static string LoginNotFound {
            get {
                return ResourceManager.GetString("LoginNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginVerb {
            get {
                return ResourceManager.GetString("LoginVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user:.
        /// </summary>
        public static string ManageUserColon {
            get {
                return ResourceManager.GetString("ManageUserColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark as done.
        /// </summary>
        public static string MarkAsDone {
            get {
                return ResourceManager.GetString("MarkAsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name or last name too short!.
        /// </summary>
        public static string NamesMinLengthWarning {
            get {
                return ResourceManager.GetString("NamesMinLengthWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer.
        /// </summary>
        public static string NewClient {
            get {
                return ResourceManager.GetString("NewClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New document type.
        /// </summary>
        public static string NewDocType {
            get {
                return ResourceManager.GetString("NewDocType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New language.
        /// </summary>
        public static string NewLanguage {
            get {
                return ResourceManager.GetString("NewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User:.
        /// </summary>
        public static string NewUserColon {
            get {
                return ResourceManager.GetString("NewUserColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer was not selected!.
        /// </summary>
        public static string NoClientWarning {
            get {
                return ResourceManager.GetString("NoClientWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database not found! If it&apos;s first start-up select &quot;Yes&quot; to create new database.
        /// </summary>
        public static string NoDbBoxText {
            get {
                return ResourceManager.GetString("NoDbBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection with database!.
        /// </summary>
        public static string NoDbBoxTitle {
            get {
                return ResourceManager.GetString("NoDbBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline not selected!.
        /// </summary>
        public static string NoDeadlineWarning {
            get {
                return ResourceManager.GetString("NoDeadlineWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type not selected!.
        /// </summary>
        public static string NoDocTypeWarning {
            get {
                return ResourceManager.GetString("NoDocTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not selected!.
        /// </summary>
        public static string NoRoleChosenWarning {
            get {
                return ResourceManager.GetString("NoRoleChosenWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language is not selected!.
        /// </summary>
        public static string NoSourceLangWarning {
            get {
                return ResourceManager.GetString("NoSourceLangWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target language is not selected!.
        /// </summary>
        public static string NoTargetLangWarning {
            get {
                return ResourceManager.GetString("NoTargetLangWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show statistics.
        /// </summary>
        public static string OpenStatisticsWindow {
            get {
                return ResourceManager.GetString("OpenStatisticsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string PasswordColon {
            get {
                return ResourceManager.GetString("PasswordColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not the same!.
        /// </summary>
        public static string PasswordsNotSameWarning {
            get {
                return ResourceManager.GetString("PasswordsNotSameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password too short!.
        /// </summary>
        public static string PasswordTooShortWarning {
            get {
                return ResourceManager.GetString("PasswordTooShortWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank.
        /// </summary>
        public static string Rank {
            get {
                return ResourceManager.GetString("Rank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:.
        /// </summary>
        public static string RankColon {
            get {
                return ResourceManager.GetString("RankColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        public static string Responsible {
            get {
                return ResourceManager.GetString("Responsible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source language.
        /// </summary>
        public static string SourceLang {
            get {
                return ResourceManager.GetString("SourceLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string SurnameColon {
            get {
                return ResourceManager.GetString("SurnameColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target language.
        /// </summary>
        public static string TargetLang {
            get {
                return ResourceManager.GetString("TargetLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        public static string Translator {
            get {
                return ResourceManager.GetString("Translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User rank NOK!.
        /// </summary>
        public static string UserLevelWarning {
            get {
                return ResourceManager.GetString("UserLevelWarning", resourceCulture);
            }
        }
    }
}
